[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "backend"
version = "0.1.0"
description = "FastAPI backend service"
authors = [{ name = "Unchanted" }]
dependencies = ["fastapi", "uvicorn[standard]"]
